In [37]:
import torch

print("PyTorch Version:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))
else:
    print("Uh oh, CUDA isn't available. We might need to check your NVIDIA drivers.")

PyTorch Version: 2.12.0+cpu
CUDA Available: False
Uh oh, CUDA isn't available. We might need to check your NVIDIA drivers.


### Creating Tensor


In [35]:
# Scalar
scalar = torch.tensor(7)
print("scalar value: ", scalar)
print("scalar dimension: ", scalar.ndim)
print("scalar item: ", scalar.item())

scalar value:  tensor(7)
scalar dimension:  0
scalar item:  7


In [10]:
# Vector
vector = torch.Tensor([7, 7])
print("vector value: ", vector)
print("vector dimension: ", vector.ndim)
print("vector shape: ", vector.shape.numel())


vector value:  tensor([7., 7.])
vector dimension:  1
vector shape:  2


In [ ]:
# Matrix 
matrix = torch.tensor([[7, 8], [9, 10]])
print("matrix value: ", matrix)
print("matrix dimension: ", matrix.ndim)
print("matrix shape: ", matrix.shape)

matrix value:  tensor([[ 7,  8],
        [ 9, 10]])
matrix dimension:  2
matrix shape:  torch.Size([2, 2])


In [11]:
# Create a random tesnsor
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.dtype

(tensor([[0.2579, 0.4702, 0.2053, 0.6789],
         [0.2121, 0.3593, 0.2730, 0.5700],
         [0.4200, 0.0477, 0.2648, 0.9901]]),
 torch.float32)

In [12]:
# Create a tensor containing numbers from 0 to 100
zero_to_hundred = torch.arange(start=0, end=101, step=1)
zero_to_hundred

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100])

In [36]:
torch.cuda.is_available()

False

### Getting information from tensors

In [15]:
# Creat a tensor
some_tensor = torch.rand(3, 4)

# Find details about the tensor
print(some_tensor)
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.6537, 0.9702, 0.7295, 0.6348],
        [0.7138, 0.4065, 0.0902, 0.7526],
        [0.4810, 0.5933, 0.6961, 0.5844]])
Shape of the tensor: torch.Size([3, 4])
Datatype of the tensor: torch.float32
Device tensor is stored on: cpu


### Operations

`torch.matmul` is all you need


In [17]:
tensor = torch.rand(3, 4)
tensor_transpose = torch.transpose(tensor, 0, 1)
print(torch.matmul(tensor, tensor_transpose))
print(torch.matmul(tensor_transpose, tensor))

tensor([[1.8081, 1.2478, 1.2777],
        [1.2478, 1.5071, 0.9124],
        [1.2777, 0.9124, 1.4753]])
tensor([[1.0836, 0.4542, 1.2358, 0.8112],
        [0.4542, 0.6853, 0.7341, 0.3130],
        [1.2358, 0.7341, 1.7266, 1.3044],
        [0.8112, 0.3130, 1.3044, 1.2951]])


### Experiment with Linear function
$$y=x\cdot{A^T} + b$$

In [19]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=3, out_features=4)
x = torch.tensor([[1., 2., 3.],
            [4., 5., 6.],
            [7., 8., 9.],
            [10., 11., 12.]])
output = linear(x)
print(f"input shape: {x.shape}")
print(f"weigth shape: {linear.weight.shape}")
print(f"output shape: {output.shape}")
print(f"output: {output}")

input shape: torch.Size([4, 3])
weigth shape: torch.Size([4, 3])
output shape: torch.Size([4, 4])
output: tensor([[1.4206, 0.7051, 2.2023, 0.8228],
        [3.7767, 2.2662, 3.9031, 1.3817],
        [6.1327, 3.8273, 5.6040, 1.9407],
        [8.4888, 5.3883, 7.3048, 2.4997]], grad_fn=<AddmmBackward0>)


### Reshaping

In [20]:
# Create a tensor 
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [22]:
# Add extra dimension to the tensor
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# View a tensor
z = x.view(1, 9)
z, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]))

In [25]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [26]:
# Rearrange the order of axes values with torch.permute()
x_original = torch.rand(244, 224, 3)
x_permuted = x_original.permute(2, 0, 1)
print(x_original.shape)
print(x_permuted.shape)

torch.Size([244, 224, 3])
torch.Size([3, 244, 224])


### Pytorch from numpy

In [28]:
import torch
import numpy as np
array = np.array([1, 2, 3, 4, 5,])
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1, 2, 3, 4, 5]), tensor([1., 2., 3., 4., 5.]))

In [29]:
!nvidia-smi

Sat May 16 11:32:14 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 571.59                 Driver Version: 571.59         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX 4000 Ada Gene...  WDDM  |   00000000:01:00.0  On |                  Off |
| 30%   31C    P8             13W /  130W |    4056MiB /  20475MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----